### ISSUE TITLE
Error: getaddrinfo ENOTFOUND api.tap.company api.tap.company:443

### ISSUE THREAD

**Issue by Amin-Shah** [Tap-Payments/goSell-JSLib-Documentation#4]
While using @tap-payments/gosell checkout module,it gives us tap_id in URL while we are sending get request using this URL = (https://api.tap.company/v2/charges/tap_id) to get response. 
const response = await axios.get('https://api.tap.company/v2/charges/' + tap_id, {
        headers: {
            'Authorization': 'Bearer sk_test_xxx'
        }
    })
Following error has been occured in IIS Server using Nodejs library and  template engine (Ejs);

Error: getaddrinfo ENOTFOUND api.tap.company api.tap.company:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)

**Comment by halaq** [comment]
Hi @Amin-Shah 
Sorry for the delay 

You're calling charge API from client side after create transaction by @tap-payments/gosell checkout module.. right?

**Comment by Amin-Shah** [comment]
No we are calling charge api from backend after redirect from gosell
lightbox. i think gosell lightbox didn't redirect us after click submit
button.

**Comment by halaq** [comment]
ok I got it. 
First, Don't share your secret key for public again please. 
Second, no need to call charge API since you're using @tap-payments/gosell checkout module. Just define the `< GoSell  />` (with your public key and transaction mode details only) in your redirect page, the result will be shown automatically.
